# Generated by Django 3.2.8 on 2021-10-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
                ('evo', models.IntegerField(verbose_name='evo')),
                ('game_id', models.CharField(max_length=50, verbose_name='g_id')),
            ],
        ),
    ]
