# Generated by Django 3.2.8 on 2021-10-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_id',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default=0, max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
